[dnb.head]
charset = "utf-8"
viewport = "width=device-width, initial-scale=1"
nobase = true

[dnb.head.styles]
entrypoint = "scss/style.scss"

[dnb.head.styles.options]
#transpiler = "dartsass"
outputStyle = "compressed"
targetPath = "assets/theme.css"
enableSourceMap = true
